### PR TITLE
Add functionality to query the content type of a path

### PR DESCRIPTION
**Pull request by egli**
using probeContentType from java.nio.file.Files

Seems fairly natural to add this functionality. 

Tests are added and they pass

### CODE REVIEW

**Comment by Raynes** [comment]
Happy to merge if the conflicts get resolved. It's only been two years. :sob:

**Comment by Raynes** [comment]
Actually, even fixing the merge conflicts there are known issues with this method returning null on common systems. Gonna close.

**Comment by egli** [comment]
I'm using com.novemberain/pantomime to determine the mime type of a file now.

**Comment by Raynes** [comment]
Yeah, this library is maintenance mode. Java 7 and 8 have great stuff.

**Pull request closed without merging**
